version: '2'
services:
    app:
        container_name: "controle-financeiro-api"
        image: node:5.9.1
        working_dir: /usr/app
        volumes:
            - .:/usr/app
        mem_limit: 512mb
        memswap_limit: 512mb
        environment:
            NODE_ENV: "dev-db-local"
            DB_URL: "mongodb://localhost:27017/controle-financeiro-db"
        command: "npm start"
        network_mode: "host"
    mongo:
        container_name: "controle-financeiro-db"
        image: mongo:3.4.14
        network_mode: "host"
